In [51]:
import numpy as np
a=np.array([[[1,2,3,4,5,6,7,8,9,10],[11,12,13,14,15,16,17,18,19,20]],[[1,2,3,4,5,6,7,8,9,10],[11,12,13,14,15,16,17,18,19,20]]])
print(a[1,:9])

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]


In [21]:
b=np.array([[11,12,13,14],[15,16,17,18]])

In [31]:
print(b[1,-2:])

[17 18]


In [41]:
print(a[::2,::2])

[[1 3 5 7 9]]


In [47]:
print(a[1,1:6])

[12 13 14 15 16]


In [50]:
print(a[0:, 4])

[ 5 15]


In [56]:
print(b[2:3,2])

[]


In [58]:
d=a.astype(bool)
print(d)

[[[ True  True  True  True  True  True  True  True  True  True]
  [ True  True  True  True  True  True  True  True  True  True]]

 [[ True  True  True  True  True  True  True  True  True  True]
  [ True  True  True  True  True  True  True  True  True  True]]]


In [74]:
import numpy as np

x=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])

y=x.reshape(1,4,5)
print(y)
y2=len(x)
print(y2)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]]]
20


In [64]:
x1=np.array([1,2,3,4,5,6])
x2=np.array([7,8,9,10,11,12])
y1=x1.reshape(2,3,2)
print(y1)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [75]:
len(x)

20

In [81]:
x1=np.array([1,2,3,4,5,6])
x2=np.array([7,8,9,10,11,12])
arr=np.hstack((x1, x2))
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [82]:
x1=np.array([1,2,3,4,5,6])
x2=np.array([7,8,9,10,11,12])
arr=np.vstack((x1, x2))
print(arr)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [86]:
x1=np.array([1,2,3,4,5])
x2=np.array([7,8,9,10,11])
arr=np.dstack((x1, x2))
print(arr)

[[[ 1  7]
  [ 2  8]
  [ 3  9]
  [ 4 10]
  [ 5 11]]]


In [88]:
split=np.array_split(x1,2)
split

[array([1, 2, 3]), array([4, 5])]

In [ ]:
m=int(input("Enter your number:"))
for i in range(m):
    n=np.array(i)
    print(n)

In [ ]:
m=int(input("Enter your number:"))
for i in range(m):
    n=np.array([i])
    print(n)

In [ ]:
g=np.array([4,65,24,53])

a1 = []
for i in g:
    if i>=6:
        a1.append(True)
    else:
        a1.append(False)

b1 = arr[a1]

print(a1)
print(b1)